name: Laravel CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      DB_CONNECTION: sqlite
      DB_DATABASE: ':memory:'
      CACHE_STORE: array
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      MAIL_MAILER: array

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, dom, fileinfo, pdo_sqlite 
          tools: composer:v2
          coverage: none

      - name: prepare dependencies
        run: cp .env.example .env

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Generate application key
        run: php artisan key:generate --no-interaction
      
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: npm

      - name: Build Frontend
        run: |
          npm ci
          npm run build

      - name: Run Tests
        run: vendor/bin/phpunit
        